name: hametkro
description: "Hametkro — Marché de seconde main 🇨🇮. Achetez, vendez, donnez une seconde vie (Côte d'Ivoire & Afrique)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Backend Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  # État
  provider: ^6.1.1

  # Images & publication
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
